### ISSUE TITLE
TODO: github-action에 chatgpt 적용해서, 코드리뷰 자동으로 적용하기

### ISSUE THREAD

**Issue by americanomin** [101market/fast-grill-url#44]
### 해볼만한 것
- [ ] 원본 코드 까보기 
- [ ] github action 설정해보기 
- [ ] chatgpt key 설정방법 확인하기
https://github.com/marketplace/actions/code-review-with-chatgpt
https://github.com/anc95/ChatGPT-CodeReview

**Comment by americanomin** [comment]
한국어로 번역이 안되는 이유가 궁금해서 코드를 까봄. 
그런데 한국어로 답변해달라는 프롬프트를 전달하는 수준이라.. 왜 한국어로 안되는지는 모르겠음.

### 코드위치
https://github.com/anc95/ChatGPT-CodeReview/blob/main/src/chat.ts#L16-L24
<img width="1074" alt="스크린샷 2023-04-12 오후 11 30 33" src="https://user-images.githubusercontent.com/10669355/231490195-6284fdfe-5c84-44a3-9057-3a5764cdc749.png">

### 프롬프트
프롬프트가 문제인건가 싶어서, 똑같이 질문해봤는데 한글로 잘 대답함. 
<img width="679" alt="스크린샷 2023-04-12 오후 11 32 27" src="https://user-images.githubusercontent.com/10669355/231490748-f7bb81ef-e625-4e1c-9921-a461ab765b34.png">
